// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVCApplKamPublic.Data;

#nullable disable

namespace WebMVCApplKamPublic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230308194150_FirstDatabase")]
    partial class FirstDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");
#pragma warning restore 612, 618
        }
    }
}
